services:
  demo-producer:
    build:
      context: "./demo_producer"
      dockerfile: Dockerfile
    ports:
      - "80:8080"
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
